services:
  mcpo:
    build: .
    ports:
      - "8000:8000"
    environment:
      - NODE_VERSION=22
      - NODE_OPTIONS=--max-old-space-size=4096
    command: >
      mcpo 
      --host 0.0.0.0 
      --port 8000 
      --cors-allow-origins "*"
      --config /app/config/mcpo-config.json
    volumes:
      - /tmp:/tmp
    networks:
      - coolify
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/docs"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

networks:
  coolify:
    external: true
